# Generated by Django 4.1 on 2022-08-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='상품명')),
                ('target', models.IntegerField(max_length=11, null=True, verbose_name='목표 인원')),
                ('people', models.IntegerField(default=0, max_length=11, null=True, verbose_name='참여 인원')),
                ('price', models.IntegerField(verbose_name='상품가격')),
                ('place', models.TextField(null=True, verbose_name='수령 장소')),
                ('buy_link', models.TextField(null=True, verbose_name='구매 페이지')),
                ('description', models.TextField(verbose_name='상품 설명')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='등록 시간')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'db_table': 'products',
            },
        ),
    ]
