# Generated by Django 4.0.6 on 2022-07-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('fno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=80, null=True)),
                ('page', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'food',
                'managed': False,
            },
        ),
    ]
